-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 18:25:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Comandos DDL para a criação do banco completo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema construtora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema construtora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `construtora` DEFAULT CHARACTER SET utf8 ;
USE `construtora` ;

-- -----------------------------------------------------
-- Table `construtora`.`CARGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`CARGOS` (
  `pk_cod_cargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`pk_cod_cargo`));


-- -----------------------------------------------------
-- Table `construtora`.`SETORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`SETORES` (
  `pk_cod_setor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`pk_cod_setor`));


-- -----------------------------------------------------
-- Table `construtora`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`FUNCIONARIOS` (
  `pk_cod_funcionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `fk_cod_cargos` INT UNSIGNED NOT NULL,
  `fk_cod_setor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pk_cod_funcionario`, `fk_cod_cargos`, `fk_cod_setor`),
  INDEX `fk_FUNCIONARIOS_CARGOS1_idx` (`fk_cod_cargos` ASC) VISIBLE,
  INDEX `fk_FUNCIONARIOS_SETORES1_idx` (`fk_cod_setor` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIOS_CARGOS1`
    FOREIGN KEY (`fk_cod_cargos`)
    REFERENCES `construtora`.`CARGOS` (`pk_cod_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIOS_SETORES1`
    FOREIGN KEY (`fk_cod_setor`)
    REFERENCES `construtora`.`SETORES` (`pk_cod_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `construtora`.`PROJETOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`PROJETOS` (
  `pk_cod_projeto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `abreviatura` VARCHAR(25) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`pk_cod_projeto`));


-- -----------------------------------------------------
-- Table `construtora`.`PROJETOS_TEM_FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construtora`.`PROJETOS_TEM_FUNCIONARIOS` (
  `fk_cod_projeto` INT NOT NULL,
  `fk_cod_funcionario` INT NOT NULL,
  PRIMARY KEY (`fk_cod_projeto`, `fk_cod_funcionario`),
  INDEX `fk_projetos_has_funcionarios_funcionarios1_idx` (`fk_cod_funcionario` ASC) VISIBLE,
  INDEX `fk_projetos_has_funcionarios_projetos_idx` (`fk_cod_projeto` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_has_funcionarios_projetos`
    FOREIGN KEY (`fk_cod_projeto`)
    REFERENCES `construtora`.`PROJETOS` (`pk_cod_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_has_funcionarios_funcionarios1`
    FOREIGN KEY (`fk_cod_funcionario`)
    REFERENCES `construtora`.`FUNCIONARIOS` (`pk_cod_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
